package com.xianzhi.fridge.recipe.application;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.xianzhi.fridge.identity.application.UserPreferenceService;
import com.xianzhi.fridge.fridge.infrastructure.FridgeRepository;
import com.xianzhi.fridge.inventory.api.InventoryContracts;
import com.xianzhi.fridge.inventory.application.InventoryService;
import com.xianzhi.fridge.inventory.domain.TransactionType;
import com.xianzhi.fridge.nutrition.api.MealContracts;
import com.xianzhi.fridge.nutrition.application.MealService;
import com.xianzhi.fridge.recipe.api.RecipeContracts;
import com.xianzhi.fridge.recipe.infrastructure.RecipeStore;
import com.xianzhi.fridge.shared.application.IdempotencyService;
import com.xianzhi.fridge.shared.domain.Hashing;
import com.xianzhi.fridge.shared.domain.UuidV7;
import com.xianzhi.fridge.shared.web.ApiException;
import java.math.*;
import java.time.Clock;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class RecipeService {
    private final RecipeStore store;private final UserPreferenceService preferences;private final InventoryService inventory;private final MealService meals;private final IdempotencyService idempotency;private final ObjectMapper mapper;private final Clock clock;private final RecipeVectorIndex vectorIndex;private final FridgeRepository fridges;private RecipeGenerationPort generation;
    public RecipeService(RecipeStore store,UserPreferenceService preferences,InventoryService inventory,MealService meals,IdempotencyService idempotency,ObjectMapper mapper,Clock clock,RecipeVectorIndex vectorIndex,FridgeRepository fridges){this.store=store;this.preferences=preferences;this.inventory=inventory;this.meals=meals;this.idempotency=idempotency;this.mapper=mapper;this.clock=clock;this.vectorIndex=vectorIndex;this.fridges=fridges;}
    @Autowired public void setGeneration(RecipeGenerationPort generation){this.generation=generation;}
    public List<RecipeContracts.RecipeView> list(UUID userId,Integer maxCook,String taste,String cuisine,BigDecimal maxCalories,String goal,String availability,String query){Set<String> exclusions=exclusions(userId);List<RecipeStore.Row> candidates;if(blank(query))candidates=store.all();else{List<UUID> vectorIds=vectorIndex.search(query,20);candidates=vectorIds.isEmpty()?store.search(query):store.byIds(vectorIds);}return candidates.stream().filter(r->safe(r,exclusions)).filter(r->maxCook==null||r.cookMinutes()<=maxCook).filter(r->blank(taste)||taste.equalsIgnoreCase(r.taste())).filter(r->blank(cuisine)||cuisine.equalsIgnoreCase(r.cuisine())).filter(r->blank(goal)||goal.equalsIgnoreCase(r.goal())).filter(r->maxCalories==null||r.calories()==null||r.calories().compareTo(maxCalories)<=0).map(r->viewV2(userId,r,List.of())).filter(v->blank(availability)||availability.equalsIgnoreCase(v.availability())).toList();}
    public RecipeContracts.RecipeView get(UUID userId,UUID id){RecipeStore.Row row=owned(id);Set<String> exclusions=exclusions(userId);if(!safe(row,exclusions))throw new ApiException(HttpStatus.NOT_FOUND,"RECIPE_NOT_FOUND","Recipe not found");return viewV2(userId,row,List.of());}
    public List<RecipeContracts.RecipeView> generate(UUID userId,RecipeContracts.GenerateRequest request){return generateResult(userId,request).recipes();}
    public GenerationResult generateResult(UUID userId,RecipeContracts.GenerateRequest request){List<RecipeContracts.IngredientInput> supplied=validated(userId,request.inventory());String prompt=request.prompt()==null?"":request.prompt().trim();int count=request.count()==null?3:Math.min(3,Math.max(1,request.count()));var preference=preferences.get(userId);Set<String> exclusions=exclusions(preference);List<ScoredRecipe> eligible=store.all().stream().filter(r->safe(r,exclusions)).map(r->score(r,prompt,supplied,preference)).sorted(Comparator.comparingInt(ScoredRecipe::score).reversed().thenComparing(v->v.row().title())).toList();List<ScoredRecipe> scored=prompt.isBlank()?eligible:eligible.stream().filter(v->v.score()>0).toList();if(scored.isEmpty())scored=eligible;if(scored.isEmpty())return new GenerationResult(List.of(),"没有找到符合当前条件的已发布菜谱","rules-v2",true);List<RecipeGenerationPort.Candidate> candidates=scored.stream().limit(20).map(v->candidate(v.row(),supplied,v.missing())).toList();RecipeGenerationPort.GeneratedRecipes ranked=generation==null?new RecipeGenerationPort.GeneratedRecipes(candidates.stream().limit(count).map(RecipeGenerationPort.Candidate::id).toList(),"根据库存、偏好和营养目标排序","rules-v2",true):generation.rank(prompt,candidates,supplied,preference.tastes(),preference.cuisines(),preference.dietaryGoal(),preference.calorieTarget(),count);Map<UUID,ScoredRecipe> byId=new HashMap<>();eligible.forEach(v->byId.put(v.row().id(),v));List<RecipeContracts.RecipeView> recipes=ranked.recipeIds().stream().map(byId::get).filter(Objects::nonNull).map(v->viewV2(userId,v.row(),supplied)).limit(count).toList();return new GenerationResult(recipes,ranked.rationale(),ranked.model(),ranked.fallback());}
    @Transactional public RecipeContracts.MatchView match(UUID userId,RecipeContracts.MatchRequest request){List<RecipeContracts.IngredientInput> inputs=validated(userId,request.ingredients());Set<String> provided=new LinkedHashSet<>();inputs.forEach(i->provided.add(i.name()));Set<String> exclusions=exclusions(userId);List<RecipeContracts.RecipeView> recipes=store.all().stream().filter(r->safe(r,exclusions)).map(r->viewV2(userId,r,inputs)).filter(v->v.missing().size()<=2).sorted(Comparator.comparingInt(v->v.missing().size())).limit(5).toList();Set<String> matched=new LinkedHashSet<>();for(var recipe:recipes)for(var component:recipe.ingredients())if(provided.stream().anyMatch(v->similar(v,component.name())))matched.add(component.name());List<String> unmatched=provided.stream().filter(v->matched.stream().noneMatch(m->similar(v,m))).toList();List<String> suggestions=recipes.stream().flatMap(v->v.missing().stream()).distinct().limit(5).toList();UUID synthesisId=UuidV7.next();try{store.synthesis(synthesisId,userId,recipes.isEmpty()?null:recipes.getFirst().id(),mapper.writeValueAsString(request),recipes.isEmpty()?"UNMATCHED":"MATCHED");}catch(JsonProcessingException e){throw new IllegalStateException(e);}return new RecipeContracts.MatchView(synthesisId,recipes,new ArrayList<>(matched),unmatched,suggestions);}
    public RecipeContracts.ScaleView scale(UUID userId,UUID id,RecipeContracts.ScaleRequest request){RecipeStore.Row row=owned(id);List<RecipeContracts.Component> base=store.components(id);RecipeContracts.Component primary=base.stream().filter(v->v.id().equals(request.primaryComponentId())).findFirst().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"RECIPE_COMPONENT_NOT_FOUND","Recipe component not found"));if(!primary.unit().equals(request.unit()))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"UNIT_NOT_CONVERTIBLE","Primary ingredient unit is not convertible");BigDecimal ratio=request.quantity().divide(primary.quantity(),8,RoundingMode.HALF_UP);List<RecipeContracts.Component> scaled=base.stream().map(c->scale(c,ratio)).toList();BigDecimal nutritionScale=ratio;RecipeContracts.Nutrition total=nutrition(row,nutritionScale);return new RecipeContracts.ScaleView(id,request.servings(),scaled,total,divide(total,request.servings()));}
    @Transactional public void bookmark(UUID userId,UUID id){owned(id);store.bookmark(userId,id,UuidV7.next());store.event(UuidV7.next(),userId,id,"BOOKMARKED","{}");}
    @Transactional public void unbookmark(UUID userId,UUID id){owned(id);store.unbookmark(userId,id);store.event(UuidV7.next(),userId,id,"UNBOOKMARKED","{}");}
    public List<RecipeContracts.PlannedRecipeView> plans(UUID userId,UUID fridgeId){requireFridge(userId,fridgeId);return store.plans(userId,fridgeId).stream().map(row->planView(userId,row)).toList();}
    @Transactional public RecipeContracts.PlannedRecipeView addPlan(UUID userId,UUID fridgeId,RecipeContracts.PlanCreateRequest request){requireFridge(userId,fridgeId);owned(request.recipeId());RecipeStore.PlanRow row=store.savePlan(UuidV7.next(),userId,fridgeId,request.recipeId(),request.servings());store.event(UuidV7.next(),userId,request.recipeId(),"PLANNED","{}");return planView(userId,row);}
    @Transactional public RecipeContracts.PlannedRecipeView updatePlan(UUID userId,UUID id,RecipeContracts.PlanUpdateRequest request){RecipeStore.PlanRow row=store.updatePlan(userId,id,request.servings());if(row==null)throw new ApiException(HttpStatus.NOT_FOUND,"RECIPE_PLAN_NOT_FOUND","Planned recipe not found");return planView(userId,row);}
    @Transactional public void deletePlan(UUID userId,UUID id){RecipeStore.PlanRow row=store.plan(userId,id);if(row==null||!store.deletePlan(userId,id))throw new ApiException(HttpStatus.NOT_FOUND,"RECIPE_PLAN_NOT_FOUND","Planned recipe not found");store.event(UuidV7.next(),userId,row.recipeId(),"UNPLANNED","{}");}
    @Transactional public RecipeContracts.CookView cook(UUID userId,UUID id,String key,RecipeContracts.CookRequest request){String path="/api/v1/recipes/"+id+"/cook";RecipeContracts.CookView replay=idempotency.replay(userId,key,"POST",path,request,RecipeContracts.CookView.class);if(replay!=null)return replay;RecipeStore.Row row=owned(id);if(request.synthesisId()!=null&&!store.executeSynthesis(userId,request.synthesisId(),id))throw new ApiException(HttpStatus.CONFLICT,"SYNTHESIS_CONTEXT_INVALID","Synthesis session is missing, stale, or belongs to another recipe");List<UUID> batchIds=new ArrayList<>();int index=0;for(var use:request.consumptions()){String nested="cook-"+Hashing.sha256(userId+":"+key+":"+index++).substring(0,64);inventory.transact(userId,use.batchId(),nested,new InventoryContracts.TransactionRequest(TransactionType.CONSUME,use.quantity(),use.unit(),"RECIPE_COOK"));batchIds.add(use.batchId());}BigDecimal factor=request.servings().divide(row.servings(),8,RoundingMode.HALF_UP);RecipeContracts.Nutrition n=nutrition(row,factor);UUID mealId=request.recordMeal()?meals.recordRecipe(userId,id,request.mealAt()==null?clock.instant():request.mealAt(),request.servings(),row.title(),new MealContracts.NutritionView(n.calories(),n.protein(),n.fat(),n.carbs(),false,row.nutritionSource(),MealService.DISCLAIMER)):null;try{store.event(UuidV7.next(),userId,id,"COOKED",mapper.writeValueAsString(Map.of("batchIds",batchIds,"synthesisId",request.synthesisId()==null?"":request.synthesisId().toString())));}catch(JsonProcessingException e){throw new IllegalStateException(e);}RecipeContracts.CookView result=new RecipeContracts.CookView(id,batchIds,mealId);idempotency.save(userId,key,"POST",path,request,result,200);return result;}
    private RecipeContracts.RecipeView view(UUID userId,RecipeStore.Row row,List<RecipeContracts.IngredientInput> supplied,Set<String> exclusions){return viewV2(userId,row,supplied);}
    private RecipeContracts.RecipeView viewV2(UUID userId,RecipeStore.Row row,List<RecipeContracts.IngredientInput> supplied){List<RecipeContracts.Component> components=store.components(row.id());List<String> warnings=new ArrayList<>();List<String> missing=supplied.isEmpty()?List.of():components.stream().filter(component->!"SEASONING".equals(component.role())).filter(component->!satisfies(component,supplied,warnings)).map(RecipeContracts.Component::name).toList();String availability=supplied.isEmpty()?"UNKNOWN":missing.isEmpty()?"DIRECT":missing.size()<=2?"MISSING_FEW":"UNMATCHED";RecipeContracts.Nutrition total=nutrition(row,BigDecimal.ONE);List<String> steps=store.steps(row.id());return new RecipeContracts.RecipeView(row.id(),row.title(),row.summary(),row.cuisine(),row.taste(),row.goal(),row.cookMinutes(),row.servings(),total,divide(total,row.servings()),components,steps,detailedSteps(row,steps),utensils(row,steps),row.nutritionSource(),store.bookmarked(userId,row.id()),row.origin(),row.sourceVersion(),row.attribution(),row.imageUrl(),row.imageSourceUrl(),row.imageAttribution(),availability,missing,warnings);}
    private List<RecipeContracts.IngredientInput> validated(UUID userId,List<RecipeContracts.IngredientInput> values){if(values==null)return List.of();return values.stream().filter(value->value.batchId()==null||inventory.isUsableForRecipe(userId,value.batchId(),value.quantity(),value.unit())).toList();}
    private boolean satisfies(RecipeContracts.Component component,List<RecipeContracts.IngredientInput> supplied,List<String> warnings){for(var input:supplied){if(!similar(input.name(),component.name()))continue;if(input.unit()==null||!input.unit().equals(component.unit())){warnings.add("UNIT_NOT_COMPARABLE:"+component.name());continue;}if(input.quantity()==null||input.quantity().compareTo(component.quantity())>=0)return true;}return false;}
    private boolean safe(RecipeStore.Row row,Set<String> exclusions){return exclusions.stream().noneMatch(excluded->store.components(row.id()).stream().anyMatch(component->similar(excluded,component.name())));}
    private Set<String> exclusions(UUID userId){return exclusions(preferences.get(userId));}
    private static Set<String> exclusions(com.xianzhi.fridge.identity.api.PreferenceContracts.View p){Set<String> values=new LinkedHashSet<>(p.allergies());values.addAll(p.dislikes());return values;}
    private ScoredRecipe score(RecipeStore.Row row,String prompt,List<RecipeContracts.IngredientInput> supplied,com.xianzhi.fridge.identity.api.PreferenceContracts.View preference){List<RecipeContracts.Component> components=store.components(row.id());int matched=0;int missing=0;for(var component:components)if(!"SEASONING".equals(component.role())){if(supplied.stream().anyMatch(i->similar(i.name(),component.name())))matched++;else missing++;}int score=matched*12-missing*7;if(prompt.isBlank())score+=8;else{String normalized=prompt.toLowerCase(Locale.ROOT);String title=row.title().toLowerCase(Locale.ROOT);String summary=row.summary()==null?"":row.summary().toLowerCase(Locale.ROOT);if(title.contains(normalized))score+=80;if(summary.contains(normalized))score+=20;for(var component:components){String ingredient=component.name().toLowerCase(Locale.ROOT);if(normalized.contains(ingredient)||ingredient.contains(normalized))score+=45;}for(String attribute:Arrays.asList(row.taste(),row.cuisine(),row.goal()))if(attribute!=null&&normalized.contains(attribute.toLowerCase(Locale.ROOT)))score+=20;for(String token:tokens(normalized))if(title.contains(token)||summary.contains(token)||components.stream().anyMatch(c->c.name().toLowerCase(Locale.ROOT).contains(token)))score+=10;}if(preference.tastes().stream().anyMatch(v->v.equalsIgnoreCase(row.taste())))score+=8;if(preference.cuisines().stream().anyMatch(v->v.equalsIgnoreCase(row.cuisine())))score+=8;if(preference.dietaryGoal()!=null&&preference.dietaryGoal().contains("减脂")&&row.calories()!=null&&row.calories().compareTo(BigDecimal.valueOf(500))<=0)score+=8;if(preference.calorieTarget()!=null&&row.calories()!=null&&row.calories().compareTo(BigDecimal.valueOf(preference.calorieTarget()))<=0)score+=4;return new ScoredRecipe(row,score,missing,matched);}
    private RecipeGenerationPort.Candidate candidate(RecipeStore.Row row,List<RecipeContracts.IngredientInput> supplied,int missing){List<RecipeContracts.Component> components=store.components(row.id());int matched=(int)components.stream().filter(c->!"SEASONING".equals(c.role())).filter(c->supplied.stream().anyMatch(i->similar(i.name(),c.name()))).count();return new RecipeGenerationPort.Candidate(row.id(),row.title(),row.summary(),row.cuisine(),row.taste(),row.goal(),row.cookMinutes(),components.stream().map(RecipeContracts.Component::name).toList(),matched,missing);}
    private static List<String> tokens(String value){return Arrays.stream(value.split("[\\s,，、。；;]+" )).map(String::trim).filter(v->v.length()>=2).toList();}
    private RecipeStore.Row owned(UUID id){return store.find(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"RECIPE_NOT_FOUND","Recipe not found"));}
    private void requireFridge(UUID userId,UUID fridgeId){if(fridgeId==null||fridges.findById(fridgeId).filter(fridge->userId.equals(fridge.getUserId())&&fridge.getDeletedAt()==null).isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"FRIDGE_NOT_FOUND","Fridge not found");}
    private RecipeContracts.PlannedRecipeView planView(UUID userId,RecipeStore.PlanRow row){RecipeStore.Row recipe=owned(row.recipeId());return new RecipeContracts.PlannedRecipeView(row.id(),row.fridgeId(),row.recipeId(),row.servings(),row.createdAt(),viewV2(userId,recipe,List.of()));}
    private static List<RecipeContracts.DetailedStep> detailedSteps(RecipeStore.Row row,List<String> steps){int minutes=Math.max(1,(int)Math.ceil(row.cookMinutes()/(double)Math.max(1,steps.size())));List<RecipeContracts.DetailedStep> output=new ArrayList<>();for(int index=0;index<steps.size();index++){String instruction=steps.get(index);String title=instruction.matches(".*(洗|切|擦干|打散|腌).*" )?"备料":instruction.matches(".*(焯|煮开|预热).*" )?"预处理":instruction.matches(".*(炒|煎|蒸|烤|煮).*" )?"烹制":"调味装盘";String heat=instruction.matches(".*(大火|水开|沸).*" )?"大火":instruction.matches(".*(小火|慢炖|焖).*" )?"小火":instruction.matches(".*(中火|煎|炒).*" )?"中火":"按状态调整";String checkpoint=instruction.matches(".*(鸡|肉|鱼|虾).*" )?"中心熟透、没有生色再进入下一步":instruction.contains("蛋")?"蛋液凝固但仍保持嫩滑":instruction.matches(".*(蔬菜|青椒|西兰花|生菜).*" )?"颜色明亮、刚断生即可":"观察香气、颜色和质地，避免只依赖计时";output.add(new RecipeContracts.DetailedStep(index+1,title,instruction,"约 "+minutes+" 分钟",heat,checkpoint));}return output;}
    private static List<String> utensils(RecipeStore.Row row,List<String> steps){String text=row.title()+" "+String.join(" ",steps);LinkedHashSet<String> tools=new LinkedHashSet<>(List.of("菜刀","砧板"));if(text.matches(".*(蒸|清蒸).*"))tools.add("蒸锅");if(text.matches(".*(炒|翻炒|爆香).*"))tools.add("炒锅");if(text.matches(".*(煎|煎至).*"))tools.add("平底锅");if(text.matches(".*(烤|烘烤).*"))tools.add("烤箱");if(text.matches(".*(煮|焯|汤|粥|面).*"))tools.add("汤锅");if(text.matches(".*(打散|腌制|拌匀).*"))tools.add("料理碗");if(tools.size()==2)tools.add("烹饪锅具");return new ArrayList<>(tools);}
    private RecipeContracts.Component scale(RecipeContracts.Component c,BigDecimal ratio){BigDecimal q;if("FIXED".equals(c.scalingRule()))q=c.quantity();else if("BOUNDED".equals(c.scalingRule())){q=c.quantity().multiply(BigDecimal.valueOf(Math.pow(ratio.doubleValue(),0.75)));if(c.minimumQuantity()!=null)q=q.max(c.minimumQuantity());if(c.maximumQuantity()!=null)q=q.min(c.maximumQuantity());}else q=c.quantity().multiply(ratio);return new RecipeContracts.Component(c.id(),c.name(),c.role(),q.setScale(3,RoundingMode.HALF_UP),c.unit(),c.scalingRule(),c.minimumQuantity(),c.maximumQuantity());}
    private static RecipeContracts.Nutrition nutrition(RecipeStore.Row r,BigDecimal factor){return new RecipeContracts.Nutrition(mul(r.calories(),factor),mul(r.protein(),factor),mul(r.fat(),factor),mul(r.carbs(),factor));}
    private static RecipeContracts.Nutrition divide(RecipeContracts.Nutrition n,BigDecimal servings){return new RecipeContracts.Nutrition(div(n.calories(),servings),div(n.protein(),servings),div(n.fat(),servings),div(n.carbs(),servings));}
    private static BigDecimal mul(BigDecimal v,BigDecimal f){return v==null?null:v.multiply(f).setScale(3,RoundingMode.HALF_UP);}private static BigDecimal div(BigDecimal v,BigDecimal d){return v==null?null:v.divide(d,3,RoundingMode.HALF_UP);}private static boolean similar(String a,String b){return a!=null&&b!=null&&(a.contains(b)||b.contains(a));}private static boolean blank(String v){return v==null||v.isBlank();}public record GenerationResult(List<RecipeContracts.RecipeView> recipes,String rationale,String model,boolean fallback){}private record ScoredRecipe(RecipeStore.Row row,int score,int missing,int matched) { }
}
