package com.xianzhi.fridge.recipe.application;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.xianzhi.fridge.identity.application.UserPreferenceService;
import com.xianzhi.fridge.inventory.api.InventoryContracts;
import com.xianzhi.fridge.inventory.application.InventoryService;
import com.xianzhi.fridge.inventory.domain.TransactionType;
import com.xianzhi.fridge.nutrition.api.MealContracts;
import com.xianzhi.fridge.nutrition.application.MealService;
import com.xianzhi.fridge.recipe.api.RecipeContracts;
import com.xianzhi.fridge.recipe.infrastructure.RecipeStore;
import com.xianzhi.fridge.shared.application.IdempotencyService;
import com.xianzhi.fridge.shared.domain.Hashing;
import com.xianzhi.fridge.shared.domain.UuidV7;
import com.xianzhi.fridge.shared.web.ApiException;
import java.math.*;
import java.time.Clock;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class RecipeService {
    private final RecipeStore store;private final UserPreferenceService preferences;private final InventoryService inventory;private final MealService meals;private final IdempotencyService idempotency;private final ObjectMapper mapper;private final Clock clock;private final RecipeVectorIndex vectorIndex;
    public RecipeService(RecipeStore store,UserPreferenceService preferences,InventoryService inventory,MealService meals,IdempotencyService idempotency,ObjectMapper mapper,Clock clock,RecipeVectorIndex vectorIndex){this.store=store;this.preferences=preferences;this.inventory=inventory;this.meals=meals;this.idempotency=idempotency;this.mapper=mapper;this.clock=clock;this.vectorIndex=vectorIndex;}
    public List<RecipeContracts.RecipeView> list(UUID userId,Integer maxCook,String taste,String cuisine,BigDecimal maxCalories,String goal,String availability,String query){Set<String> exclusions=exclusions(userId);List<RecipeStore.Row> candidates;if(blank(query))candidates=store.all();else{List<UUID> vectorIds=vectorIndex.search(query,20);candidates=vectorIds.isEmpty()?store.search(query):store.byIds(vectorIds);}return candidates.stream().filter(r->safe(r,exclusions)).filter(r->maxCook==null||r.cookMinutes()<=maxCook).filter(r->blank(taste)||taste.equalsIgnoreCase(r.taste())).filter(r->blank(cuisine)||cuisine.equalsIgnoreCase(r.cuisine())).filter(r->blank(goal)||goal.equalsIgnoreCase(r.goal())).filter(r->maxCalories==null||r.calories()==null||r.calories().compareTo(maxCalories)<=0).map(r->viewV2(userId,r,List.of())).filter(v->blank(availability)||availability.equalsIgnoreCase(v.availability())).toList();}
    public RecipeContracts.RecipeView get(UUID userId,UUID id){RecipeStore.Row row=owned(id);Set<String> exclusions=exclusions(userId);if(!safe(row,exclusions))throw new ApiException(HttpStatus.NOT_FOUND,"RECIPE_NOT_FOUND","Recipe not found");return viewV2(userId,row,List.of());}
    public List<RecipeContracts.RecipeView> generate(UUID userId,RecipeContracts.GenerateRequest request){List<RecipeContracts.IngredientInput> supplied=validated(userId,request.inventory());String prompt=request.prompt()==null?"":request.prompt().trim();int count=request.count()==null?3:request.count();Set<String> exclusions=exclusions(userId);return store.search(prompt).stream().filter(r->safe(r,exclusions)).filter(r->prompt.isBlank()||similar(prompt,r.title())||store.components(r.id()).stream().anyMatch(c->similar(prompt,c.name()))).map(r->viewV2(userId,r,supplied)).sorted(Comparator.comparingInt(v->v.missing().size())).limit(count).toList();}
    public RecipeContracts.MatchView match(UUID userId,RecipeContracts.MatchRequest request){List<RecipeContracts.IngredientInput> inputs=validated(userId,request.ingredients());Set<String> provided=new LinkedHashSet<>();inputs.forEach(i->provided.add(i.name()));Set<String> exclusions=exclusions(userId);List<RecipeContracts.RecipeView> recipes=store.all().stream().filter(r->safe(r,exclusions)).map(r->viewV2(userId,r,inputs)).filter(v->v.missing().size()<=2).sorted(Comparator.comparingInt(v->v.missing().size())).limit(5).toList();Set<String> matched=new LinkedHashSet<>();for(var recipe:recipes)for(var component:recipe.ingredients())if(provided.stream().anyMatch(v->similar(v,component.name())))matched.add(component.name());List<String> unmatched=provided.stream().filter(v->matched.stream().noneMatch(m->similar(v,m))).toList();List<String> suggestions=recipes.stream().flatMap(v->v.missing().stream()).distinct().limit(5).toList();return new RecipeContracts.MatchView(recipes,new ArrayList<>(matched),unmatched,suggestions);}
    public RecipeContracts.ScaleView scale(UUID userId,UUID id,RecipeContracts.ScaleRequest request){RecipeStore.Row row=owned(id);List<RecipeContracts.Component> base=store.components(id);RecipeContracts.Component primary=base.stream().filter(v->v.id().equals(request.primaryComponentId())).findFirst().orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"RECIPE_COMPONENT_NOT_FOUND","Recipe component not found"));if(!primary.unit().equals(request.unit()))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"UNIT_NOT_CONVERTIBLE","Primary ingredient unit is not convertible");BigDecimal ratio=request.quantity().divide(primary.quantity(),8,RoundingMode.HALF_UP);List<RecipeContracts.Component> scaled=base.stream().map(c->scale(c,ratio)).toList();BigDecimal nutritionScale=ratio;RecipeContracts.Nutrition total=nutrition(row,nutritionScale);return new RecipeContracts.ScaleView(id,request.servings(),scaled,total,divide(total,request.servings()));}
    @Transactional public void bookmark(UUID userId,UUID id){owned(id);store.bookmark(userId,id,UuidV7.next());store.event(UuidV7.next(),userId,id,"BOOKMARKED","{}");}
    @Transactional public void unbookmark(UUID userId,UUID id){owned(id);store.unbookmark(userId,id);store.event(UuidV7.next(),userId,id,"UNBOOKMARKED","{}");}
    @Transactional public RecipeContracts.CookView cook(UUID userId,UUID id,String key,RecipeContracts.CookRequest request){String path="/api/v1/recipes/"+id+"/cook";RecipeContracts.CookView replay=idempotency.replay(userId,key,"POST",path,request,RecipeContracts.CookView.class);if(replay!=null)return replay;RecipeStore.Row row=owned(id);List<UUID> batchIds=new ArrayList<>();int index=0;for(var use:request.consumptions()){String nested="cook-"+Hashing.sha256(userId+":"+key+":"+index++).substring(0,64);inventory.transact(userId,use.batchId(),nested,new InventoryContracts.TransactionRequest(TransactionType.CONSUME,use.quantity(),use.unit(),"RECIPE_COOK"));batchIds.add(use.batchId());}BigDecimal factor=request.servings().divide(row.servings(),8,RoundingMode.HALF_UP);RecipeContracts.Nutrition n=nutrition(row,factor);UUID mealId=request.recordMeal()?meals.recordRecipe(userId,id,request.mealAt()==null?clock.instant():request.mealAt(),request.servings(),row.title(),new MealContracts.NutritionView(n.calories(),n.protein(),n.fat(),n.carbs(),false,"RECIPE_DATABASE",MealService.DISCLAIMER)):null;try{store.event(UuidV7.next(),userId,id,"COOKED",mapper.writeValueAsString(Map.of("batchIds",batchIds)));}catch(JsonProcessingException e){throw new IllegalStateException(e);}RecipeContracts.CookView result=new RecipeContracts.CookView(id,batchIds,mealId);idempotency.save(userId,key,"POST",path,request,result,200);return result;}
    private RecipeContracts.RecipeView view(UUID userId,RecipeStore.Row row,List<RecipeContracts.IngredientInput> supplied,Set<String> exclusions){List<RecipeContracts.Component> components=store.components(row.id());List<String> warnings=new ArrayList<>();for(String excluded:exclusions)if(components.stream().anyMatch(c->similar(excluded,c.name())))warnings.add("包含已设置的过敏或忌口食材："+excluded);Set<String> available=new HashSet<>();supplied.forEach(i->{if(i.quantity()==null||i.quantity().signum()>0)available.add(i.name());});List<String> missing=supplied.isEmpty()?List.of():components.stream().filter(c->!"SEASONING".equals(c.role())).map(RecipeContracts.Component::name).filter(name->available.stream().noneMatch(v->similar(v,name))).toList();String availability=supplied.isEmpty()?"UNKNOWN":missing.isEmpty()?"DIRECT":missing.size()<=2?"MISSING_FEW":"UNMATCHED";RecipeContracts.Nutrition total=nutrition(row,BigDecimal.ONE);return new RecipeContracts.RecipeView(row.id(),row.title(),row.summary(),row.cuisine(),row.taste(),row.goal(),row.cookMinutes(),row.servings(),total,divide(total,row.servings()),components,store.steps(row.id()),store.bookmarked(userId,row.id()),row.origin(),row.sourceVersion(),row.attribution(),availability,missing,warnings);}
    private RecipeContracts.RecipeView viewV2(UUID userId,RecipeStore.Row row,List<RecipeContracts.IngredientInput> supplied){List<RecipeContracts.Component> components=store.components(row.id());List<String> warnings=new ArrayList<>();List<String> missing=supplied.isEmpty()?List.of():components.stream().filter(component->!"SEASONING".equals(component.role())).filter(component->!satisfies(component,supplied,warnings)).map(RecipeContracts.Component::name).toList();String availability=supplied.isEmpty()?"UNKNOWN":missing.isEmpty()?"DIRECT":missing.size()<=2?"MISSING_FEW":"UNMATCHED";RecipeContracts.Nutrition total=nutrition(row,BigDecimal.ONE);return new RecipeContracts.RecipeView(row.id(),row.title(),row.summary(),row.cuisine(),row.taste(),row.goal(),row.cookMinutes(),row.servings(),total,divide(total,row.servings()),components,store.steps(row.id()),store.bookmarked(userId,row.id()),row.origin(),row.sourceVersion(),row.attribution(),availability,missing,warnings);}
    private List<RecipeContracts.IngredientInput> validated(UUID userId,List<RecipeContracts.IngredientInput> values){if(values==null)return List.of();return values.stream().filter(value->value.batchId()==null||inventory.isUsableForRecipe(userId,value.batchId(),value.quantity(),value.unit())).toList();}
    private boolean satisfies(RecipeContracts.Component component,List<RecipeContracts.IngredientInput> supplied,List<String> warnings){for(var input:supplied){if(!similar(input.name(),component.name()))continue;if(input.unit()==null||!input.unit().equals(component.unit())){warnings.add("UNIT_NOT_COMPARABLE:"+component.name());continue;}if(input.quantity()==null||input.quantity().compareTo(component.quantity())>=0)return true;}return false;}
    private boolean safe(RecipeStore.Row row,Set<String> exclusions){return exclusions.stream().noneMatch(excluded->store.components(row.id()).stream().anyMatch(component->similar(excluded,component.name())));}
    private Set<String> exclusions(UUID userId){var p=preferences.get(userId);Set<String> values=new LinkedHashSet<>(p.allergies());values.addAll(p.dislikes());return values;}
    private RecipeStore.Row owned(UUID id){return store.find(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"RECIPE_NOT_FOUND","Recipe not found"));}
    private RecipeContracts.Component scale(RecipeContracts.Component c,BigDecimal ratio){BigDecimal q;if("FIXED".equals(c.scalingRule()))q=c.quantity();else if("BOUNDED".equals(c.scalingRule())){q=c.quantity().multiply(BigDecimal.valueOf(Math.pow(ratio.doubleValue(),0.75)));if(c.minimumQuantity()!=null)q=q.max(c.minimumQuantity());if(c.maximumQuantity()!=null)q=q.min(c.maximumQuantity());}else q=c.quantity().multiply(ratio);return new RecipeContracts.Component(c.id(),c.name(),c.role(),q.setScale(3,RoundingMode.HALF_UP),c.unit(),c.scalingRule(),c.minimumQuantity(),c.maximumQuantity());}
    private static RecipeContracts.Nutrition nutrition(RecipeStore.Row r,BigDecimal factor){return new RecipeContracts.Nutrition(mul(r.calories(),factor),mul(r.protein(),factor),mul(r.fat(),factor),mul(r.carbs(),factor));}
    private static RecipeContracts.Nutrition divide(RecipeContracts.Nutrition n,BigDecimal servings){return new RecipeContracts.Nutrition(div(n.calories(),servings),div(n.protein(),servings),div(n.fat(),servings),div(n.carbs(),servings));}
    private static BigDecimal mul(BigDecimal v,BigDecimal f){return v==null?null:v.multiply(f).setScale(3,RoundingMode.HALF_UP);}private static BigDecimal div(BigDecimal v,BigDecimal d){return v==null?null:v.divide(d,3,RoundingMode.HALF_UP);}private static boolean similar(String a,String b){return a!=null&&b!=null&&(a.contains(b)||b.contains(a));}private static boolean blank(String v){return v==null||v.isBlank();}
}
