package com.xianzhi.fridge.nutrition.application;

import com.xianzhi.fridge.identity.infrastructure.AppUserRepository;
import com.xianzhi.fridge.nutrition.api.MealContracts;
import com.xianzhi.fridge.shared.application.IdempotencyService;
import com.xianzhi.fridge.shared.domain.UuidV7;
import com.xianzhi.fridge.shared.web.ApiException;
import java.math.*;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.HttpStatus;

@Service
public class MealService {
    public static final String DISCLAIMER="仅用于日常饮食管理，不用于疾病诊断或治疗。";
    private final JdbcTemplate jdbc;private final IdempotencyService idempotency;private final Clock clock;private final AppUserRepository users;private final MealNutritionEstimator nutritionEstimator;
    public MealService(JdbcTemplate jdbc,IdempotencyService idempotency,Clock clock,AppUserRepository users,MealNutritionEstimator nutritionEstimator){this.jdbc=jdbc;this.idempotency=idempotency;this.clock=clock;this.users=users;this.nutritionEstimator=nutritionEstimator;}
    public MealContracts.NutritionView estimate(MealContracts.EstimateRequest request){nutritionScale(request.amount(),request.unit());return nutritionEstimator.estimate(request);}
    @Transactional public MealContracts.MealView create(UUID userId,String key,MealContracts.CreateRequest request){String path="/api/v1/meals";MealContracts.MealView replay=idempotency.replay(userId,key,"POST",path,request,MealContracts.MealView.class);if(replay!=null)return replay;UUID id=insert(userId,request.recipeId(),request.mealAt(),request.mealType(),request.name(),request.servings(),request.calories(),request.protein(),request.fat(),request.carbs(),Boolean.TRUE.equals(request.estimated()),request.nutritionSource()==null?"USER_PROVIDED":request.nutritionSource());MealContracts.MealView result=find(userId,id);idempotency.save(userId,key,"POST",path,request,result,200);return result;}
    @Transactional public UUID recordRecipe(UUID userId,UUID recipeId,Instant at,BigDecimal servings,String name,MealContracts.NutritionView nutrition){return insert(userId,recipeId,at==null?clock.instant():at,null,name,servings,nutrition.calories(),nutrition.protein(),nutrition.fat(),nutrition.carbs(),nutrition.estimated(),nutrition.source());}
    @Transactional @SuppressWarnings("unchecked") public void delete(UUID userId,UUID id,String key){String path="/api/v1/meals/"+id;Map<String,Boolean> replay=idempotency.replay(userId,key,"DELETE",path,id,Map.class);if(replay!=null)return;int changed=jdbc.update("delete from meal_record where id=UUID_TO_BIN(?) and user_id=UUID_TO_BIN(?)",id.toString(),userId.toString());if(changed==0)throw new ApiException(HttpStatus.NOT_FOUND,"MEAL_NOT_FOUND","Meal record not found");idempotency.save(userId,key,"DELETE",path,id,Map.of("deleted",true),200);}
    public List<MealContracts.MealView> list(UUID userId){return jdbc.query("select BIN_TO_UUID(id) id,BIN_TO_UUID(recipe_id) recipe_id,meal_at,meal_type,name,servings,calories,protein,fat,carbs,estimated,nutrition_source,disclaimer from meal_record where user_id=UUID_TO_BIN(?) order by meal_at desc",(rs,n)->new MealContracts.MealView(UUID.fromString(rs.getString("id")),rs.getString("recipe_id")==null?null:UUID.fromString(rs.getString("recipe_id")),rs.getTimestamp("meal_at").toInstant(),rs.getString("meal_type"),rs.getString("name"),rs.getBigDecimal("servings"),new MealContracts.NutritionView(rs.getBigDecimal("calories"),rs.getBigDecimal("protein"),rs.getBigDecimal("fat"),rs.getBigDecimal("carbs"),rs.getBoolean("estimated"),rs.getString("nutrition_source"),rs.getString("disclaimer"))),userId.toString());}
    public MealContracts.DietView diet(UUID userId,LocalDate date){ZoneId zone=ZoneId.of(users.findById(userId).orElseThrow().getTimezone());LocalDate selected=date==null?LocalDate.now(clock.withZone(zone)):date;Instant from=selected.atStartOfDay(zone).toInstant(),to=selected.plusDays(1).atStartOfDay(zone).toInstant();return jdbc.queryForObject("select coalesce(sum(calories),0),coalesce(sum(protein),0),coalesce(sum(fat),0),coalesce(sum(carbs),0),count(*) from meal_record where user_id=UUID_TO_BIN(?) and meal_at>=? and meal_at<?",(rs,n)->new MealContracts.DietView(from,to,rs.getBigDecimal(1),rs.getBigDecimal(2),rs.getBigDecimal(3),rs.getBigDecimal(4),rs.getInt(5),DISCLAIMER),userId.toString(),Timestamp.from(from),Timestamp.from(to));}
    public MealContracts.ConsumptionView consumption(UUID userId,String period){int days="month".equalsIgnoreCase(period)?30:7;Instant from=clock.instant().minus(Duration.ofDays(days));List<MealContracts.ConsumptionItem> top=jdbc.query("select i.display_name,sum(-t.quantity_delta) quantity,t.unit,count(*) transactions from inventory_transaction t join inventory_batch b on b.id=t.batch_id join inventory_item i on i.id=b.item_id where t.actor_user_id=UUID_TO_BIN(?) and t.type='CONSUME' and t.deleted_at is null and t.created_at>=? group by i.display_name,t.unit order by quantity desc,transactions desc,i.display_name limit 5",(rs,n)->new MealContracts.ConsumptionItem(rs.getString("display_name"),rs.getBigDecimal("quantity"),rs.getString("unit"),rs.getInt("transactions")),userId.toString(),Timestamp.from(from));return jdbc.queryForObject("select coalesce(sum(case when t.type='CONSUME' then -t.quantity_delta else 0 end),0),coalesce(sum(case when t.type='DISCARD' then -t.quantity_delta else 0 end),0),coalesce(sum(case when t.type='EXPIRED' then -t.quantity_delta else 0 end),0) from inventory_transaction t where t.actor_user_id=UUID_TO_BIN(?) and t.deleted_at is null and t.created_at>=?",(rs,n)->new MealContracts.ConsumptionView(period,rs.getBigDecimal(1),rs.getBigDecimal(2),rs.getBigDecimal(3),"MIXED",top),userId.toString(),Timestamp.from(from));}
    private UUID insert(UUID userId,UUID recipeId,Instant at,String type,String name,BigDecimal servings,BigDecimal calories,BigDecimal protein,BigDecimal fat,BigDecimal carbs,boolean estimated,String source){UUID id=UuidV7.next();jdbc.update("insert into meal_record(id,user_id,recipe_id,meal_at,meal_type,name,servings,calories,protein,fat,carbs,estimated,nutrition_source,disclaimer,created_at,updated_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",id.toString(),userId.toString(),recipeId==null?null:recipeId.toString(),Timestamp.from(at),type,name,servings,calories,protein,fat,carbs,estimated,source,DISCLAIMER);return id;}
    private MealContracts.MealView find(UUID userId,UUID id){return list(userId).stream().filter(v->v.id().equals(id)).findFirst().orElseThrow();}
    static BigDecimal nutritionScale(BigDecimal amount,String unit){String value=unit==null?"serving":unit.trim().toLowerCase(Locale.ROOT);if(!Set.of("g","ml","kg","serving","piece","box","bottle","bag","cup").contains(value))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"UNIT_NOT_CONVERTIBLE","Nutrition estimate unit is not supported");if(amount==null||amount.signum()<=0)return BigDecimal.ONE;return switch(value){case "g","ml"->amount.divide(BigDecimal.valueOf(250),4,RoundingMode.HALF_UP);case "kg"->amount.multiply(BigDecimal.valueOf(4));default->amount;};}
    private static BigDecimal mul(BigDecimal value,BigDecimal scale){return value==null?null:value.multiply(scale).setScale(3,RoundingMode.HALF_UP);}
}
