package com.xianzhi.fridge.nutrition.application;

import com.xianzhi.fridge.identity.infrastructure.AppUserRepository;
import com.xianzhi.fridge.nutrition.api.MealContracts;
import com.xianzhi.fridge.shared.application.IdempotencyService;
import com.xianzhi.fridge.shared.domain.UuidV7;
import com.xianzhi.fridge.shared.web.ApiException;
import java.math.*;
import java.sql.Timestamp;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.HttpStatus;

@Service
public class MealService {
    public static final String DISCLAIMER="仅用于日常饮食管理，不用于疾病诊断或治疗。";
    private final JdbcTemplate jdbc;private final IdempotencyService idempotency;private final Clock clock;private final AppUserRepository users;
    public MealService(JdbcTemplate jdbc,IdempotencyService idempotency,Clock clock,AppUserRepository users){this.jdbc=jdbc;this.idempotency=idempotency;this.clock=clock;this.users=users;}
    public MealContracts.NutritionView estimate(MealContracts.EstimateRequest request){var row=jdbc.query("select calories_total,protein_total,fat_total,carbs_total,title from recipe where review_status='APPROVED' and title like ? limit 1",(rs,n)->new BigDecimal[]{rs.getBigDecimal(1),rs.getBigDecimal(2),rs.getBigDecimal(3),rs.getBigDecimal(4)},"%"+request.dishName().trim()+"%").stream().findFirst().orElse(null);BigDecimal scale=nutritionScale(request.amount(),request.unit());if(row==null){BigDecimal calories=BigDecimal.valueOf(Math.max(80,Math.min(760,request.dishName().length()*58L+110))).multiply(scale);return new MealContracts.NutritionView(calories,calories.multiply(new BigDecimal("0.075")),null,null,true,"RULE_ESTIMATE",DISCLAIMER);}return new MealContracts.NutritionView(mul(row[0],scale),mul(row[1],scale),mul(row[2],scale),mul(row[3],scale),false,"RECIPE_DATABASE",DISCLAIMER);}
    @Transactional public MealContracts.MealView create(UUID userId,String key,MealContracts.CreateRequest request){String path="/api/v1/meals";MealContracts.MealView replay=idempotency.replay(userId,key,"POST",path,request,MealContracts.MealView.class);if(replay!=null)return replay;UUID id=insert(userId,request.recipeId(),request.mealAt(),request.mealType(),request.name(),request.servings(),request.calories(),request.protein(),request.fat(),request.carbs(),Boolean.TRUE.equals(request.estimated()),request.nutritionSource()==null?"USER_PROVIDED":request.nutritionSource());MealContracts.MealView result=find(userId,id);idempotency.save(userId,key,"POST",path,request,result,200);return result;}
    @Transactional public UUID recordRecipe(UUID userId,UUID recipeId,Instant at,BigDecimal servings,String name,MealContracts.NutritionView nutrition){return insert(userId,recipeId,at==null?clock.instant():at,null,name,servings,nutrition.calories(),nutrition.protein(),nutrition.fat(),nutrition.carbs(),nutrition.estimated(),nutrition.source());}
    public List<MealContracts.MealView> list(UUID userId){return jdbc.query("select BIN_TO_UUID(id) id,BIN_TO_UUID(recipe_id) recipe_id,meal_at,meal_type,name,servings,calories,protein,fat,carbs,estimated,nutrition_source,disclaimer from meal_record where user_id=UUID_TO_BIN(?) order by meal_at desc",(rs,n)->new MealContracts.MealView(UUID.fromString(rs.getString("id")),rs.getString("recipe_id")==null?null:UUID.fromString(rs.getString("recipe_id")),rs.getTimestamp("meal_at").toInstant(),rs.getString("meal_type"),rs.getString("name"),rs.getBigDecimal("servings"),new MealContracts.NutritionView(rs.getBigDecimal("calories"),rs.getBigDecimal("protein"),rs.getBigDecimal("fat"),rs.getBigDecimal("carbs"),rs.getBoolean("estimated"),rs.getString("nutrition_source"),rs.getString("disclaimer"))),userId.toString());}
    public MealContracts.DietView diet(UUID userId,LocalDate date){ZoneId zone=ZoneId.of(users.findById(userId).orElseThrow().getTimezone());LocalDate selected=date==null?LocalDate.now(clock.withZone(zone)):date;Instant from=selected.atStartOfDay(zone).toInstant(),to=selected.plusDays(1).atStartOfDay(zone).toInstant();return jdbc.queryForObject("select coalesce(sum(calories),0),coalesce(sum(protein),0),coalesce(sum(fat),0),coalesce(sum(carbs),0),count(*) from meal_record where user_id=UUID_TO_BIN(?) and meal_at>=? and meal_at<?",(rs,n)->new MealContracts.DietView(from,to,rs.getBigDecimal(1),rs.getBigDecimal(2),rs.getBigDecimal(3),rs.getBigDecimal(4),rs.getInt(5),DISCLAIMER),userId.toString(),Timestamp.from(from),Timestamp.from(to));}
    public MealContracts.ConsumptionView consumption(UUID userId,String period){int days="month".equalsIgnoreCase(period)?30:7;Instant from=clock.instant().minus(Duration.ofDays(days));return jdbc.queryForObject("select coalesce(sum(case when t.type='CONSUME' then -t.quantity_delta else 0 end),0),coalesce(sum(case when t.type='DISCARD' then -t.quantity_delta else 0 end),0),coalesce(sum(case when t.type='EXPIRED' then -t.quantity_delta else 0 end),0) from inventory_transaction t where t.actor_user_id=UUID_TO_BIN(?) and t.created_at>=?",(rs,n)->new MealContracts.ConsumptionView(period,rs.getBigDecimal(1),rs.getBigDecimal(2),rs.getBigDecimal(3),"MIXED"),userId.toString(),Timestamp.from(from));}
    private UUID insert(UUID userId,UUID recipeId,Instant at,String type,String name,BigDecimal servings,BigDecimal calories,BigDecimal protein,BigDecimal fat,BigDecimal carbs,boolean estimated,String source){UUID id=UuidV7.next();jdbc.update("insert into meal_record(id,user_id,recipe_id,meal_at,meal_type,name,servings,calories,protein,fat,carbs,estimated,nutrition_source,disclaimer,created_at,updated_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",id.toString(),userId.toString(),recipeId==null?null:recipeId.toString(),Timestamp.from(at),type,name,servings,calories,protein,fat,carbs,estimated,source,DISCLAIMER);return id;}
    private MealContracts.MealView find(UUID userId,UUID id){return list(userId).stream().filter(v->v.id().equals(id)).findFirst().orElseThrow();}
    static BigDecimal nutritionScale(BigDecimal amount,String unit){if(amount==null||amount.signum()<=0)return BigDecimal.ONE;String value=unit==null?"serving":unit.trim().toLowerCase(Locale.ROOT);return switch(value){case "g","ml"->amount.divide(BigDecimal.valueOf(250),4,RoundingMode.HALF_UP);case "kg"->amount.multiply(BigDecimal.valueOf(4));case "serving","piece","box","bottle","bag","cup"->amount;default->throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"UNIT_NOT_CONVERTIBLE","Nutrition estimate unit is not supported");};}
    private static BigDecimal mul(BigDecimal value,BigDecimal scale){return value==null?null:value.multiply(scale).setScale(3,RoundingMode.HALF_UP);}
}
