package com.xianzhi.fridge.assistant.infrastructure;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.xianzhi.fridge.assistant.api.AssistantContracts;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class AssistantStore {
    private final JdbcTemplate jdbc;private final ObjectMapper mapper;public AssistantStore(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;}
    public AssistantContracts.ConversationView conversation(UUID id,UUID userId){try{return jdbc.queryForObject("select BIN_TO_UUID(id) id,title,status,created_at from assistant_conversation where id=UUID_TO_BIN(?) and user_id=UUID_TO_BIN(?)",(rs,n)->new AssistantContracts.ConversationView(UUID.fromString(rs.getString("id")),rs.getString("title"),rs.getString("status"),rs.getTimestamp("created_at").toInstant()),id.toString(),userId.toString());}catch(EmptyResultDataAccessException e){return null;}}
    public AssistantContracts.ConversationView createConversation(UUID id,UUID userId,String title,Instant now){jdbc.update("insert into assistant_conversation(id,user_id,title,status,created_at,updated_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),?,'ACTIVE',?,?)",id.toString(),userId.toString(),title,Timestamp.from(now),Timestamp.from(now));return new AssistantContracts.ConversationView(id,title,"ACTIVE",now);}
    public UUID snapshot(UUID id,UUID userId,String version,String context,String sources,Instant expires,Instant now){jdbc.update("insert ignore into ai_context_snapshot(id,user_id,context_version,context_json,source_versions,expires_at,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),?,CAST(? AS JSON),CAST(? AS JSON),?,?)",id.toString(),userId.toString(),version,context,sources,Timestamp.from(expires),Timestamp.from(now));String existing=jdbc.queryForObject("select BIN_TO_UUID(id) from ai_context_snapshot where user_id=UUID_TO_BIN(?) and context_version=?",String.class,userId.toString(),version);return UUID.fromString(existing);}
    public AssistantContracts.MessageView message(UUID id,UUID conversationId,UUID userId,String role,String content,String page,String selection,String citations,UUID snapshotId,String version,String model,String status,Instant now){jdbc.update("insert into assistant_message(id,conversation_id,user_id,role,content,page,selection_json,citations_json,context_snapshot_id,context_version,model_name,generation_status,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),?,?,?,?,CAST(? AS JSON),UUID_TO_BIN(?),?,?,?,?)",id.toString(),conversationId.toString(),userId.toString(),role,content,page,selection,citations,snapshotId==null?null:snapshotId.toString(),version,model,status,Timestamp.from(now));jdbc.update("update assistant_conversation set updated_at=? where id=UUID_TO_BIN(?)",Timestamp.from(now),conversationId.toString());return new AssistantContracts.MessageView(id,role,content,version,now);}
    public AssistantContracts.ProposalView proposal(UUID id,UUID userId,UUID conversationId,String type,String title,String payload,String version,Instant expires,Instant now){jdbc.update("insert into assistant_action_proposal(id,user_id,conversation_id,action_type,title,payload_json,context_version,status,expires_at,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),?,?,CAST(? AS JSON),?,'PENDING_CONFIRMATION',?,?)",id.toString(),userId.toString(),conversationId.toString(),type,title,payload,version,Timestamp.from(expires),Timestamp.from(now));return new AssistantContracts.ProposalView(id,type,title,"PENDING_CONFIRMATION",version,json(payload),expires);}
    public ProposalRow proposalRow(UUID id,UUID userId){try{return jdbc.queryForObject("select BIN_TO_UUID(id) id,action_type,title,payload_json,context_version,status,expires_at from assistant_action_proposal where id=UUID_TO_BIN(?) and user_id=UUID_TO_BIN(?)",(rs,n)->new ProposalRow(UUID.fromString(rs.getString("id")),rs.getString("action_type"),rs.getString("title"),rs.getString("payload_json"),rs.getString("context_version"),rs.getString("status"),rs.getTimestamp("expires_at").toInstant()),id.toString(),userId.toString());}catch(EmptyResultDataAccessException e){return null;}}
    public void complete(UUID id,String status,String result,Instant now){String timeColumn="CONFIRMED".equals(status)?"confirmed_at":"dismissed_at";jdbc.update("update assistant_action_proposal set status=?,result_json=CAST(? AS JSON),"+timeColumn+"=? where id=UUID_TO_BIN(?)",status,result,Timestamp.from(now),id.toString());}
    public int pending(UUID userId){Integer v=jdbc.queryForObject("select count(*) from assistant_action_proposal where user_id=UUID_TO_BIN(?) and status='PENDING_CONFIRMATION' and expires_at>UTC_TIMESTAMP(3)",Integer.class,userId.toString());return v==null?0:v;}
    public int unreadNotifications(UUID userId){Integer v=jdbc.queryForObject("select count(*) from notification where user_id=UUID_TO_BIN(?) and in_app_visible=true and read_at is null and dismissed_at is null",Integer.class,userId.toString());return v==null?0:v;}
    public List<AssistantContracts.InsightView> insights(UUID userId){return jdbc.query("select BIN_TO_UUID(id) id,insight_type,title,body,created_at from assistant_insight where user_id=UUID_TO_BIN(?) and status='ACTIVE' order by created_at desc limit 10",(rs,n)->new AssistantContracts.InsightView(UUID.fromString(rs.getString("id")),rs.getString("insight_type"),rs.getString("title"),rs.getString("body"),rs.getTimestamp("created_at").toInstant()),userId.toString());}
    private JsonNode json(String value){try{return mapper.readTree(value);}catch(Exception e){return mapper.createObjectNode();}}
    public record ProposalRow(UUID id,String type,String title,String payload,String contextVersion,String status,Instant expiresAt){}
}
