package com.xianzhi.fridge.recipe.infrastructure;

import com.xianzhi.fridge.recipe.api.RecipeContracts;
import com.xianzhi.fridge.recipe.application.RecipeImportParser;
import com.xianzhi.fridge.shared.domain.UuidV7;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class RecipeStore {
    private final JdbcTemplate jdbc; public RecipeStore(JdbcTemplate jdbc){this.jdbc=jdbc;}
    public List<Row> all(){return jdbc.query("select BIN_TO_UUID(r.id) id,r.title,r.summary,r.cuisine,r.taste,r.goal,r.cook_minutes,r.servings,r.calories_total,r.protein_total,r.fat_total,r.carbs_total,r.origin,r.source_version,r.attribution_text from recipe r where r.review_status='APPROVED' order by r.created_at desc",(rs,n)->new Row(UUID.fromString(rs.getString("id")),rs.getString("title"),rs.getString("summary"),rs.getString("cuisine"),rs.getString("taste"),rs.getString("goal"),rs.getInt("cook_minutes"),rs.getBigDecimal("servings"),rs.getBigDecimal("calories_total"),rs.getBigDecimal("protein_total"),rs.getBigDecimal("fat_total"),rs.getBigDecimal("carbs_total"),rs.getString("origin"),rs.getString("source_version"),rs.getString("attribution_text")));}
    public List<Row> search(String query){if(query==null||query.isBlank())return all();List<Row> rows=jdbc.query("select BIN_TO_UUID(r.id) id,r.title,r.summary,r.cuisine,r.taste,r.goal,r.cook_minutes,r.servings,r.calories_total,r.protein_total,r.fat_total,r.carbs_total,r.origin,r.source_version,r.attribution_text from recipe r where r.review_status='APPROVED' and MATCH(r.title,r.summary) AGAINST (? IN NATURAL LANGUAGE MODE) order by MATCH(r.title,r.summary) AGAINST (? IN NATURAL LANGUAGE MODE) desc",this::row,query,query);if(!rows.isEmpty())return rows;rows=jdbc.query("select distinct BIN_TO_UUID(r.id) id,r.title,r.summary,r.cuisine,r.taste,r.goal,r.cook_minutes,r.servings,r.calories_total,r.protein_total,r.fat_total,r.carbs_total,r.origin,r.source_version,r.attribution_text from recipe r join recipe_knowledge_chunk k on k.recipe_id=r.id where r.review_status='APPROVED' and MATCH(k.content_text) AGAINST (? IN NATURAL LANGUAGE MODE) order by r.title",this::row,query);if(!rows.isEmpty())return rows;String pattern="%"+query+"%";return jdbc.query("select distinct BIN_TO_UUID(r.id) id,r.title,r.summary,r.cuisine,r.taste,r.goal,r.cook_minutes,r.servings,r.calories_total,r.protein_total,r.fat_total,r.carbs_total,r.origin,r.source_version,r.attribution_text from recipe r left join recipe_component c on c.recipe_id=r.id where r.review_status='APPROVED' and (r.title like ? or r.summary like ? or c.name like ?) order by r.title",this::row,pattern,pattern,pattern);}
    public List<Row> byIds(List<UUID> ids){if(ids==null||ids.isEmpty())return List.of();Map<UUID,Row> found=new HashMap<>();for(Row value:all())if(ids.contains(value.id()))found.put(value.id(),value);return ids.stream().map(found::get).filter(Objects::nonNull).toList();}
    public Optional<Row> find(UUID id){return all().stream().filter(v->v.id().equals(id)).findFirst();}
    public List<RecipeContracts.Component> components(UUID recipeId){return jdbc.query("select BIN_TO_UUID(id) id,name,role,quantity,unit,scaling_rule,minimum_quantity,maximum_quantity from recipe_component where recipe_id=UUID_TO_BIN(?) order by sort_order",(rs,n)->new RecipeContracts.Component(UUID.fromString(rs.getString("id")),rs.getString("name"),rs.getString("role"),rs.getBigDecimal("quantity"),rs.getString("unit"),rs.getString("scaling_rule"),rs.getBigDecimal("minimum_quantity"),rs.getBigDecimal("maximum_quantity")),recipeId.toString());}
    public List<String> steps(UUID recipeId){return jdbc.query("select instruction_text from recipe_step where recipe_id=UUID_TO_BIN(?) order by step_number",(rs,n)->rs.getString(1),recipeId.toString());}
    public boolean bookmarked(UUID userId,UUID recipeId){Integer count=jdbc.queryForObject("select count(*) from recipe_bookmark where user_id=UUID_TO_BIN(?) and recipe_id=UUID_TO_BIN(?)",Integer.class,userId.toString(),recipeId.toString());return count!=null&&count>0;}
    public void bookmark(UUID userId,UUID recipeId,UUID id){jdbc.update("insert ignore into recipe_bookmark(id,user_id,recipe_id,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),UTC_TIMESTAMP(3))",id.toString(),userId.toString(),recipeId.toString());}
    public void unbookmark(UUID userId,UUID recipeId){jdbc.update("delete from recipe_bookmark where user_id=UUID_TO_BIN(?) and recipe_id=UUID_TO_BIN(?)",userId.toString(),recipeId.toString());}
    public void event(UUID id,UUID userId,UUID recipeId,String type,String json){jdbc.update("insert into recipe_event(id,user_id,recipe_id,event_type,payload_json,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),?,CAST(? AS JSON),UTC_TIMESTAMP(3))",id.toString(),userId.toString(),recipeId.toString(),type,json);}
    public List<RecipeContracts.SourceView> sources(){return jdbc.query("select BIN_TO_UUID(id) id,name,source_type,license_code,attribution_text,allowed_use,source_version,enabled from recipe_source order by created_at desc",(rs,n)->new RecipeContracts.SourceView(UUID.fromString(rs.getString("id")),rs.getString("name"),rs.getString("source_type"),rs.getString("license_code"),rs.getString("attribution_text"),rs.getString("allowed_use"),rs.getString("source_version"),rs.getBoolean("enabled")));}
    public RecipeContracts.SourceView createSource(UUID id,RecipeContracts.SourceRequest r){jdbc.update("insert into recipe_source(id,name,source_type,license_code,attribution_text,allowed_use,source_version,enabled,created_at,updated_at) values(UUID_TO_BIN(?),?,?,?,?,?,?,?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",id.toString(),r.name().trim(),r.sourceType(),r.licenseCode(),r.attributionText(),r.allowedUse(),r.sourceVersion(),r.enabled()==null||r.enabled());return new RecipeContracts.SourceView(id,r.name().trim(),r.sourceType(),r.licenseCode(),r.attributionText(),r.allowedUse(),r.sourceVersion(),r.enabled()==null||r.enabled());}
    public RecipeContracts.SourceView updateSource(UUID id,RecipeContracts.SourceRequest r){int changed=jdbc.update("update recipe_source set name=?,source_type=?,license_code=?,attribution_text=?,allowed_use=?,source_version=?,enabled=?,updated_at=UTC_TIMESTAMP(3) where id=UUID_TO_BIN(?)",r.name().trim(),r.sourceType(),r.licenseCode(),r.attributionText(),r.allowedUse(),r.sourceVersion(),r.enabled()==null||r.enabled(),id.toString());if(changed==0)return null;return new RecipeContracts.SourceView(id,r.name().trim(),r.sourceType(),r.licenseCode(),r.attributionText(),r.allowedUse(),r.sourceVersion(),r.enabled()==null||r.enabled());}
    public RecipeContracts.ImportJobView importJob(UUID id,UUID sourceId,UUID userId,String payload,String checksum){jdbc.update("insert into recipe_import_job(id,source_id,requested_by,status,payload_json,checksum,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),'QUEUED',CAST(? AS JSON),?,UTC_TIMESTAMP(3))",id.toString(),sourceId.toString(),userId.toString(),payload,checksum);return getImport(id);}
    public RecipeContracts.ImportJobView findImport(UUID sourceId,String checksum){try{return jdbc.queryForObject("select BIN_TO_UUID(id) id,BIN_TO_UUID(source_id) source_id,status,checksum,imported_count,skipped_count,error_count,created_at,completed_at from recipe_import_job where source_id=UUID_TO_BIN(?) and checksum=?",(rs,n)->new RecipeContracts.ImportJobView(UUID.fromString(rs.getString("id")),UUID.fromString(rs.getString("source_id")),rs.getString("status"),rs.getString("checksum"),rs.getInt("imported_count"),rs.getInt("skipped_count"),rs.getInt("error_count"),instant(rs.getTimestamp("created_at")),instant(rs.getTimestamp("completed_at"))),sourceId.toString(),checksum);}catch(EmptyResultDataAccessException e){return null;}}
    public RecipeContracts.ImportJobView getImport(UUID id){try{return jdbc.queryForObject("select BIN_TO_UUID(id) id,BIN_TO_UUID(source_id) source_id,status,checksum,imported_count,skipped_count,error_count,created_at,completed_at from recipe_import_job where id=UUID_TO_BIN(?)",(rs,n)->new RecipeContracts.ImportJobView(UUID.fromString(rs.getString("id")),UUID.fromString(rs.getString("source_id")),rs.getString("status"),rs.getString("checksum"),rs.getInt("imported_count"),rs.getInt("skipped_count"),rs.getInt("error_count"),instant(rs.getTimestamp("created_at")),instant(rs.getTimestamp("completed_at"))),id.toString());}catch(EmptyResultDataAccessException e){return null;}}
    public List<ImportWork> claimImports(int limit){List<ImportWork> rows=jdbc.query("select BIN_TO_UUID(j.id) id,BIN_TO_UUID(j.source_id) source_id,j.payload_json,s.source_version,s.attribution_text from recipe_import_job j join recipe_source s on s.id=j.source_id where j.status='QUEUED' or (j.status='PROCESSING' and j.locked_at<UTC_TIMESTAMP(3)-INTERVAL 10 MINUTE) order by j.created_at limit ? for update skip locked",(rs,n)->new ImportWork(UUID.fromString(rs.getString("id")),UUID.fromString(rs.getString("source_id")),rs.getString("payload_json"),rs.getString("source_version"),rs.getString("attribution_text")),limit);for(ImportWork row:rows)jdbc.update("update recipe_import_job set status='PROCESSING',started_at=coalesce(started_at,UTC_TIMESTAMP(3)),locked_at=UTC_TIMESTAMP(3) where id=UUID_TO_BIN(?)",row.id().toString());return rows;}
    public boolean fingerprintExists(String fingerprint){Integer count=jdbc.queryForObject("select count(*) from recipe where normalized_fingerprint=?",Integer.class,fingerprint);return count!=null&&count>0;}
    public UUID insertImportedRecipe(ImportWork work,RecipeImportParser.RecipeDocument document){UUID recipeId=UuidV7.next();jdbc.update("insert into recipe(id,source_id,source_recipe_id,source_version,origin,title,summary,cuisine,taste,goal,cook_minutes,servings,calories_total,protein_total,fat_total,carbs_total,normalized_fingerprint,review_status,attribution_text,created_at,updated_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'APPROVED',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",recipeId.toString(),work.sourceId().toString(),document.sourceRecipeId(),work.sourceVersion(),"IMPORTED",document.title(),document.summary(),document.cuisine(),document.taste(),document.goal(),document.cookMinutes(),document.servings(),document.calories(),document.protein(),document.fat(),document.carbs(),document.fingerprint(),work.attribution());for(var component:document.components())jdbc.update("insert into recipe_component(id,recipe_id,name,role,quantity,unit,scaling_rule,minimum_quantity,maximum_quantity,sort_order) values(UUID_TO_BIN(?),UUID_TO_BIN(?),?,?,?,?,?,?,?,?)",UuidV7.next().toString(),recipeId.toString(),component.name(),component.role(),component.quantity(),component.unit(),component.scalingRule(),component.minimumQuantity(),component.maximumQuantity(),component.sortOrder());int step=0;for(String instruction:document.steps())jdbc.update("insert into recipe_step(id,recipe_id,step_number,instruction_text) values(UUID_TO_BIN(?),UUID_TO_BIN(?),?,?)",UuidV7.next().toString(),recipeId.toString(),++step,instruction);String searchable=document.title()+"\n"+(document.summary()==null?"":document.summary())+"\n"+document.components().stream().map(RecipeImportParser.ComponentDocument::name).reduce((a,b)->a+" "+b).orElse("");jdbc.update("insert into recipe_knowledge_chunk(id,recipe_id,chunk_type,content_text,source_version,attribution_text,index_status,created_at,updated_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),'SUMMARY',?,?,?,'MYSQL_INDEXED',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",UuidV7.next().toString(),recipeId.toString(),searchable,work.sourceVersion(),work.attribution());jdbc.update("insert into recipe_search_index_state(recipe_id,mysql_indexed_at,status,updated_at) values(UUID_TO_BIN(?),UTC_TIMESTAMP(3),'MYSQL_ONLY',UTC_TIMESTAMP(3))",recipeId.toString());jdbc.update("insert into recipe_version(id,recipe_id,version_number,snapshot_json,checksum,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),1,CAST(? AS JSON),?,UTC_TIMESTAMP(3))",UuidV7.next().toString(),recipeId.toString(),document.snapshot(),document.snapshotChecksum());return recipeId;}
    public void markVector(UUID recipeId,boolean indexed,String failure){jdbc.update("update recipe_knowledge_chunk set index_status=?,updated_at=UTC_TIMESTAMP(3) where recipe_id=UUID_TO_BIN(?)",indexed?"VECTOR_INDEXED":"MYSQL_INDEXED",recipeId.toString());jdbc.update("update recipe_search_index_state set vector_indexed_at=?,status=?,failure_reason=?,updated_at=UTC_TIMESTAMP(3) where recipe_id=UUID_TO_BIN(?)",indexed?Timestamp.from(Instant.now()):null,indexed?"READY":"MYSQL_ONLY",failure,recipeId.toString());}
    public void completeImport(UUID id,int imported,int skipped,List<String> errors){String status=errors.isEmpty()?"COMPLETED":"COMPLETED_WITH_ERRORS";String errorJson=errors.isEmpty()?null:toJson(errors);jdbc.update("update recipe_import_job set status=?,imported_count=?,skipped_count=?,error_count=?,error_json=CAST(? AS JSON),completed_at=UTC_TIMESTAMP(3),locked_at=null where id=UUID_TO_BIN(?)",status,imported,skipped,errors.size(),errorJson,id.toString());}
    public void failImport(UUID id,String error){jdbc.update("update recipe_import_job set status='FAILED',error_count=1,error_json=JSON_ARRAY(?),completed_at=UTC_TIMESTAMP(3),locked_at=null where id=UUID_TO_BIN(?)",error,id.toString());}
    private String toJson(List<String> values){try{return new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(values);}catch(Exception exception){return "[]";}}
    private Row row(java.sql.ResultSet rs,int n)throws java.sql.SQLException{return new Row(UUID.fromString(rs.getString("id")),rs.getString("title"),rs.getString("summary"),rs.getString("cuisine"),rs.getString("taste"),rs.getString("goal"),rs.getInt("cook_minutes"),rs.getBigDecimal("servings"),rs.getBigDecimal("calories_total"),rs.getBigDecimal("protein_total"),rs.getBigDecimal("fat_total"),rs.getBigDecimal("carbs_total"),rs.getString("origin"),rs.getString("source_version"),rs.getString("attribution_text"));}
    private static Instant instant(Timestamp t){return t==null?null:t.toInstant();}
    public record ImportWork(UUID id,UUID sourceId,String payload,String sourceVersion,String attribution){}
    public record Row(UUID id,String title,String summary,String cuisine,String taste,String goal,int cookMinutes,BigDecimal servings,BigDecimal calories,BigDecimal protein,BigDecimal fat,BigDecimal carbs,String origin,String sourceVersion,String attribution){}
}
