package com.xianzhi.fridge.recipe.infrastructure;

import com.xianzhi.fridge.recipe.api.RecipeContracts;
import com.xianzhi.fridge.recipe.application.RecipeImportParser;
import com.xianzhi.fridge.shared.domain.UuidV7;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class RecipeStore {
    private final JdbcTemplate jdbc; public RecipeStore(JdbcTemplate jdbc){this.jdbc=jdbc;}
    public List<Row> all(){return jdbc.query("select BIN_TO_UUID(r.id) id,r.title,r.summary,r.cuisine,r.taste,r.goal,r.cook_minutes,r.servings,r.calories_total,r.protein_total,r.fat_total,r.carbs_total,r.nutrition_source,r.origin,r.source_version,r.attribution_text,r.image_url,r.image_source_url,r.image_attribution from recipe r where r.review_status='APPROVED' order by r.created_at desc",this::row);}
    public List<Row> search(String query){if(query==null||query.isBlank())return all();List<Row> rows=jdbc.query("select BIN_TO_UUID(r.id) id,r.title,r.summary,r.cuisine,r.taste,r.goal,r.cook_minutes,r.servings,r.calories_total,r.protein_total,r.fat_total,r.carbs_total,r.nutrition_source,r.origin,r.source_version,r.attribution_text,r.image_url,r.image_source_url,r.image_attribution from recipe r where r.review_status='APPROVED' and MATCH(r.title,r.summary) AGAINST (? IN NATURAL LANGUAGE MODE) order by MATCH(r.title,r.summary) AGAINST (? IN NATURAL LANGUAGE MODE) desc",this::row,query,query);if(!rows.isEmpty())return rows;rows=jdbc.query("select distinct BIN_TO_UUID(r.id) id,r.title,r.summary,r.cuisine,r.taste,r.goal,r.cook_minutes,r.servings,r.calories_total,r.protein_total,r.fat_total,r.carbs_total,r.nutrition_source,r.origin,r.source_version,r.attribution_text,r.image_url,r.image_source_url,r.image_attribution from recipe r join recipe_knowledge_chunk k on k.recipe_id=r.id where r.review_status='APPROVED' and MATCH(k.content_text) AGAINST (? IN NATURAL LANGUAGE MODE) order by r.title",this::row,query);if(!rows.isEmpty())return rows;String pattern="%"+query+"%";return jdbc.query("select distinct BIN_TO_UUID(r.id) id,r.title,r.summary,r.cuisine,r.taste,r.goal,r.cook_minutes,r.servings,r.calories_total,r.protein_total,r.fat_total,r.carbs_total,r.nutrition_source,r.origin,r.source_version,r.attribution_text,r.image_url,r.image_source_url,r.image_attribution from recipe r left join recipe_component c on c.recipe_id=r.id where r.review_status='APPROVED' and (r.title like ? or r.summary like ? or c.name like ?) order by r.title",this::row,pattern,pattern,pattern);}
    public List<Row> byIds(List<UUID> ids){if(ids==null||ids.isEmpty())return List.of();Map<UUID,Row> found=new HashMap<>();for(Row value:all())if(ids.contains(value.id()))found.put(value.id(),value);return ids.stream().map(found::get).filter(Objects::nonNull).toList();}
    public Optional<Row> find(UUID id){return all().stream().filter(v->v.id().equals(id)).findFirst();}
    public List<RecipeContracts.Component> components(UUID recipeId){return jdbc.query("select BIN_TO_UUID(id) id,name,role,quantity,unit,scaling_rule,minimum_quantity,maximum_quantity from recipe_component where recipe_id=UUID_TO_BIN(?) order by sort_order",(rs,n)->new RecipeContracts.Component(UUID.fromString(rs.getString("id")),rs.getString("name"),rs.getString("role"),rs.getBigDecimal("quantity"),rs.getString("unit"),rs.getString("scaling_rule"),rs.getBigDecimal("minimum_quantity"),rs.getBigDecimal("maximum_quantity")),recipeId.toString());}
    public List<String> steps(UUID recipeId){return jdbc.query("select instruction_text from recipe_step where recipe_id=UUID_TO_BIN(?) order by step_number",(rs,n)->rs.getString(1),recipeId.toString());}
    public boolean bookmarked(UUID userId,UUID recipeId){Integer count=jdbc.queryForObject("select count(*) from recipe_bookmark where user_id=UUID_TO_BIN(?) and recipe_id=UUID_TO_BIN(?)",Integer.class,userId.toString(),recipeId.toString());return count!=null&&count>0;}
    public void bookmark(UUID userId,UUID recipeId,UUID id){jdbc.update("insert ignore into recipe_bookmark(id,user_id,recipe_id,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),UTC_TIMESTAMP(3))",id.toString(),userId.toString(),recipeId.toString());}
    public void unbookmark(UUID userId,UUID recipeId){jdbc.update("delete from recipe_bookmark where user_id=UUID_TO_BIN(?) and recipe_id=UUID_TO_BIN(?)",userId.toString(),recipeId.toString());}
    public List<PlanRow> plans(UUID userId,UUID fridgeId){return jdbc.query("select BIN_TO_UUID(id) id,BIN_TO_UUID(fridge_id) fridge_id,BIN_TO_UUID(recipe_id) recipe_id,servings,created_at from planned_recipe where user_id=UUID_TO_BIN(?) and fridge_id=UUID_TO_BIN(?) order by created_at desc",this::planRow,userId.toString(),fridgeId.toString());}
    public PlanRow plan(UUID userId,UUID id){List<PlanRow> values=jdbc.query("select BIN_TO_UUID(id) id,BIN_TO_UUID(fridge_id) fridge_id,BIN_TO_UUID(recipe_id) recipe_id,servings,created_at from planned_recipe where user_id=UUID_TO_BIN(?) and id=UUID_TO_BIN(?)",this::planRow,userId.toString(),id.toString());return values.isEmpty()?null:values.getFirst();}
    public PlanRow savePlan(UUID id,UUID userId,UUID fridgeId,UUID recipeId,BigDecimal servings){jdbc.update("insert into planned_recipe(id,user_id,fridge_id,recipe_id,servings,created_at,updated_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3)) on duplicate key update servings=values(servings),updated_at=UTC_TIMESTAMP(3)",id.toString(),userId.toString(),fridgeId.toString(),recipeId.toString(),servings);return plans(userId,fridgeId).stream().filter(value->value.recipeId().equals(recipeId)).findFirst().orElseThrow();}
    public PlanRow updatePlan(UUID userId,UUID id,BigDecimal servings){int changed=jdbc.update("update planned_recipe set servings=?,updated_at=UTC_TIMESTAMP(3) where user_id=UUID_TO_BIN(?) and id=UUID_TO_BIN(?)",servings,userId.toString(),id.toString());return changed==0?null:plan(userId,id);}
    public boolean deletePlan(UUID userId,UUID id){return jdbc.update("delete from planned_recipe where user_id=UUID_TO_BIN(?) and id=UUID_TO_BIN(?)",userId.toString(),id.toString())>0;}
    public void event(UUID id,UUID userId,UUID recipeId,String type,String json){jdbc.update("insert into recipe_event(id,user_id,recipe_id,event_type,payload_json,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),?,CAST(? AS JSON),UTC_TIMESTAMP(3))",id.toString(),userId.toString(),recipeId.toString(),type,json);}
    public UUID synthesis(UUID id,UUID userId,UUID recipeId,String input,String status){jdbc.update("insert into recipe_synthesis_session(id,user_id,recipe_id,input_json,status,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),CAST(? AS JSON),?,UTC_TIMESTAMP(3))",id.toString(),userId.toString(),recipeId==null?null:recipeId.toString(),input,status);return id;}
    public boolean executeSynthesis(UUID userId,UUID id,UUID recipeId){return jdbc.update("update recipe_synthesis_session set status='EXECUTED',executed_at=UTC_TIMESTAMP(3) where id=UUID_TO_BIN(?) and user_id=UUID_TO_BIN(?) and recipe_id=UUID_TO_BIN(?) and status='MATCHED'",id.toString(),userId.toString(),recipeId.toString())>0;}
    public List<RecipeContracts.SourceView> sources(){return jdbc.query("select BIN_TO_UUID(id) id,name,source_type,license_code,attribution_text,allowed_use,source_version,enabled from recipe_source order by created_at desc",(rs,n)->new RecipeContracts.SourceView(UUID.fromString(rs.getString("id")),rs.getString("name"),rs.getString("source_type"),rs.getString("license_code"),rs.getString("attribution_text"),rs.getString("allowed_use"),rs.getString("source_version"),rs.getBoolean("enabled")));}
    public RecipeContracts.SourceView createSource(UUID id,RecipeContracts.SourceRequest r){jdbc.update("insert into recipe_source(id,name,source_type,license_code,attribution_text,allowed_use,source_version,enabled,created_at,updated_at) values(UUID_TO_BIN(?),?,?,?,?,?,?,?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",id.toString(),r.name().trim(),r.sourceType(),r.licenseCode(),r.attributionText(),r.allowedUse(),r.sourceVersion(),r.enabled()==null||r.enabled());return new RecipeContracts.SourceView(id,r.name().trim(),r.sourceType(),r.licenseCode(),r.attributionText(),r.allowedUse(),r.sourceVersion(),r.enabled()==null||r.enabled());}
    public RecipeContracts.SourceView updateSource(UUID id,RecipeContracts.SourceRequest r){int changed=jdbc.update("update recipe_source set name=?,source_type=?,license_code=?,attribution_text=?,allowed_use=?,source_version=?,enabled=?,updated_at=UTC_TIMESTAMP(3) where id=UUID_TO_BIN(?)",r.name().trim(),r.sourceType(),r.licenseCode(),r.attributionText(),r.allowedUse(),r.sourceVersion(),r.enabled()==null||r.enabled(),id.toString());if(changed==0)return null;return new RecipeContracts.SourceView(id,r.name().trim(),r.sourceType(),r.licenseCode(),r.attributionText(),r.allowedUse(),r.sourceVersion(),r.enabled()==null||r.enabled());}
    public RecipeContracts.ImportJobView importJob(UUID id,UUID sourceId,UUID userId,String payload,String checksum){jdbc.update("insert into recipe_import_job(id,source_id,requested_by,status,payload_json,checksum,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),UUID_TO_BIN(?),'QUEUED',CAST(? AS JSON),?,UTC_TIMESTAMP(3))",id.toString(),sourceId.toString(),userId.toString(),payload,checksum);return getImport(id);}
    public RecipeContracts.ImportJobView findImport(UUID sourceId,String checksum){try{return jdbc.queryForObject(importSelect()+" where source_id=UUID_TO_BIN(?) and checksum=?",this::importRow,sourceId.toString(),checksum);}catch(EmptyResultDataAccessException e){return null;}}
    public RecipeContracts.ImportJobView getImport(UUID id){try{return jdbc.queryForObject(importSelect()+" where id=UUID_TO_BIN(?)",this::importRow,id.toString());}catch(EmptyResultDataAccessException e){return null;}}
    public List<RecipeContracts.ImportJobView> imports(String status,int page,int size){String filter=status==null||status.isBlank()?"":" where status=?";Object[] args=status==null||status.isBlank()?new Object[]{size,page*size}:new Object[]{status,size,page*size};return jdbc.query(importSelect()+filter+" order by created_at desc limit ? offset ?",this::importRow,args);}
    public long countImports(String status){Long value=status==null||status.isBlank()?jdbc.queryForObject("select count(*) from recipe_import_job",Long.class):jdbc.queryForObject("select count(*) from recipe_import_job where status=?",Long.class,status);return value==null?0:value;}
    public RecipeContracts.ImportJobView retryImport(UUID id){int changed=jdbc.update("update recipe_import_job set status='QUEUED',attempt_count=attempt_count+1,last_error=null,error_count=0,error_json=null,started_at=null,completed_at=null,locked_at=null where id=UUID_TO_BIN(?) and status in ('FAILED','COMPLETED_WITH_ERRORS')",id.toString());return changed==0?null:getImport(id);}
    public List<ImportWork> claimImports(int limit){List<ImportWork> rows=jdbc.query("select BIN_TO_UUID(j.id) id,BIN_TO_UUID(j.source_id) source_id,j.payload_json,s.source_version,s.attribution_text from recipe_import_job j join recipe_source s on s.id=j.source_id where j.status='QUEUED' or (j.status='PROCESSING' and j.locked_at<UTC_TIMESTAMP(3)-INTERVAL 10 MINUTE) order by j.created_at limit ? for update skip locked",(rs,n)->new ImportWork(UUID.fromString(rs.getString("id")),UUID.fromString(rs.getString("source_id")),rs.getString("payload_json"),rs.getString("source_version"),rs.getString("attribution_text")),limit);for(ImportWork row:rows)jdbc.update("update recipe_import_job set status='PROCESSING',started_at=coalesce(started_at,UTC_TIMESTAMP(3)),locked_at=UTC_TIMESTAMP(3) where id=UUID_TO_BIN(?)",row.id().toString());return rows;}
    public boolean fingerprintExists(String fingerprint){Integer count=jdbc.queryForObject("select count(*) from recipe where normalized_fingerprint=?",Integer.class,fingerprint);return count!=null&&count>0;}
    public UUID insertImportedRecipe(ImportWork work,RecipeImportParser.RecipeDocument document){UUID recipeId=UuidV7.next();jdbc.update("insert into recipe(id,source_id,source_recipe_id,source_version,origin,title,summary,cuisine,taste,goal,cook_minutes,servings,calories_total,protein_total,fat_total,carbs_total,normalized_fingerprint,review_status,attribution_text,image_url,image_source_url,image_attribution,created_at,updated_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'APPROVED',?,?,?,?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",recipeId.toString(),work.sourceId().toString(),document.sourceRecipeId(),work.sourceVersion(),"IMPORTED",document.title(),document.summary(),document.cuisine(),document.taste(),document.goal(),document.cookMinutes(),document.servings(),document.calories(),document.protein(),document.fat(),document.carbs(),document.fingerprint(),work.attribution(),document.imageUrl(),document.imageSourceUrl(),document.imageAttribution());for(var component:document.components())jdbc.update("insert into recipe_component(id,recipe_id,name,role,quantity,unit,scaling_rule,minimum_quantity,maximum_quantity,sort_order) values(UUID_TO_BIN(?),UUID_TO_BIN(?),?,?,?,?,?,?,?,?)",UuidV7.next().toString(),recipeId.toString(),component.name(),component.role(),component.quantity(),component.unit(),component.scalingRule(),component.minimumQuantity(),component.maximumQuantity(),component.sortOrder());int step=0;for(String instruction:document.steps())jdbc.update("insert into recipe_step(id,recipe_id,step_number,instruction_text) values(UUID_TO_BIN(?),UUID_TO_BIN(?),?,?)",UuidV7.next().toString(),recipeId.toString(),++step,instruction);String searchable=document.title()+"\n"+(document.summary()==null?"":document.summary())+"\n"+document.components().stream().map(RecipeImportParser.ComponentDocument::name).reduce((a,b)->a+" "+b).orElse("");jdbc.update("insert into recipe_knowledge_chunk(id,recipe_id,chunk_type,content_text,source_version,attribution_text,index_status,created_at,updated_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),'SUMMARY',?,?,?,'MYSQL_INDEXED',UTC_TIMESTAMP(3),UTC_TIMESTAMP(3))",UuidV7.next().toString(),recipeId.toString(),searchable,work.sourceVersion(),work.attribution());jdbc.update("insert into recipe_search_index_state(recipe_id,mysql_indexed_at,status,updated_at) values(UUID_TO_BIN(?),UTC_TIMESTAMP(3),'MYSQL_ONLY',UTC_TIMESTAMP(3))",recipeId.toString());jdbc.update("insert into recipe_version(id,recipe_id,version_number,snapshot_json,checksum,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),1,CAST(? AS JSON),?,UTC_TIMESTAMP(3))",UuidV7.next().toString(),recipeId.toString(),document.snapshot(),document.snapshotChecksum());return recipeId;}
    public void markVector(UUID recipeId,boolean indexed,String failure){jdbc.update("update recipe_knowledge_chunk set index_status=?,updated_at=UTC_TIMESTAMP(3) where recipe_id=UUID_TO_BIN(?)",indexed?"VECTOR_INDEXED":"MYSQL_INDEXED",recipeId.toString());jdbc.update("update recipe_search_index_state set vector_indexed_at=?,status=?,failure_reason=?,updated_at=UTC_TIMESTAMP(3) where recipe_id=UUID_TO_BIN(?)",indexed?Timestamp.from(Instant.now()):null,indexed?"READY":"MYSQL_ONLY",failure,recipeId.toString());}
    public void completeImport(UUID id,int imported,int skipped,List<String> errors){String status=errors.isEmpty()?"COMPLETED":"COMPLETED_WITH_ERRORS";String errorJson=errors.isEmpty()?null:toJson(errors);jdbc.update("update recipe_import_job set status=?,imported_count=?,skipped_count=?,error_count=?,error_json=CAST(? AS JSON),completed_at=UTC_TIMESTAMP(3),locked_at=null where id=UUID_TO_BIN(?)",status,imported,skipped,errors.size(),errorJson,id.toString());}
    public void failImport(UUID id,String error){jdbc.update("update recipe_import_job set status='FAILED',error_count=1,error_json=JSON_ARRAY(?),last_error=?,completed_at=UTC_TIMESTAMP(3),locked_at=null where id=UUID_TO_BIN(?)",error,error,id.toString());}
    public RecipeContracts.IndexRebuildJobView createRebuild(UUID id,UUID userId,String collection,String model){jdbc.update("insert into recipe_index_rebuild_job(id,requested_by,status,collection_name,embedding_model_version,created_at) values(UUID_TO_BIN(?),UUID_TO_BIN(?),'QUEUED',?,?,UTC_TIMESTAMP(3))",id.toString(),userId.toString(),collection,model);return getRebuild(id);}
    public RecipeContracts.IndexRebuildJobView getRebuild(UUID id){try{return jdbc.queryForObject(rebuildSelect()+" where id=UUID_TO_BIN(?)",this::rebuildRow,id.toString());}catch(EmptyResultDataAccessException exception){return null;}}
    public RecipeContracts.IndexRebuildJobView latestRebuild(){List<RecipeContracts.IndexRebuildJobView> values=jdbc.query(rebuildSelect()+" order by created_at desc limit 1",this::rebuildRow);return values.isEmpty()?null:values.getFirst();}
    public boolean rebuildRunning(){Integer count=jdbc.queryForObject("select count(*) from recipe_index_rebuild_job where status in ('QUEUED','PROCESSING')",Integer.class);return count!=null&&count>0;}
    public RebuildWork claimRebuild(){List<RebuildWork> rows=jdbc.query("select BIN_TO_UUID(id) id,collection_name,embedding_model_version,processed_count,failure_count from recipe_index_rebuild_job where status='QUEUED' or (status='PROCESSING' and locked_at<UTC_TIMESTAMP(3)-INTERVAL 10 MINUTE) order by created_at limit 1 for update skip locked",(rs,n)->new RebuildWork(UUID.fromString(rs.getString("id")),rs.getString("collection_name"),rs.getString("embedding_model_version"),rs.getInt("processed_count"),rs.getInt("failure_count")));if(rows.isEmpty())return null;RebuildWork row=rows.getFirst();jdbc.update("update recipe_index_rebuild_job set status='PROCESSING',started_at=coalesce(started_at,UTC_TIMESTAMP(3)),locked_at=UTC_TIMESTAMP(3),total_count=(select count(*) from recipe where review_status='APPROVED') where id=UUID_TO_BIN(?)",row.id().toString());return row;}
    public List<IndexDocument> indexDocuments(int offset,int limit){return jdbc.query("select BIN_TO_UUID(r.id) id,r.title,concat_ws('\\n',r.title,r.summary,group_concat(c.name separator ' ')) content from recipe r left join recipe_component c on c.recipe_id=r.id where r.review_status='APPROVED' group by r.id,r.title,r.summary,r.created_at order by r.created_at,r.id limit ? offset ?",(rs,n)->new IndexDocument(UUID.fromString(rs.getString("id")),rs.getString("title"),rs.getString("content")),limit,offset);}
    public void rebuildProgress(UUID id,int processed,int failures,String lastError){jdbc.update("update recipe_index_rebuild_job set processed_count=?,failure_count=?,last_error=?,locked_at=UTC_TIMESTAMP(3) where id=UUID_TO_BIN(?)",processed,failures,lastError,id.toString());}
    public void completeRebuild(UUID id,String collection,String model){jdbc.update("update recipe_index_rebuild_job set status='COMPLETED',completed_at=UTC_TIMESTAMP(3),locked_at=null,last_error=null where id=UUID_TO_BIN(?)",id.toString());jdbc.update("update recipe_search_index_config set active_collection=?,embedding_model_version=?,updated_at=UTC_TIMESTAMP(3) where singleton_id=1",collection,model);jdbc.update("update recipe_search_index_state set vector_indexed_at=UTC_TIMESTAMP(3),embedding_model_version=?,status='READY',failure_reason=null,updated_at=UTC_TIMESTAMP(3)",model);jdbc.update("update recipe_knowledge_chunk set embedding_model_version=?,index_status='VECTOR_INDEXED',updated_at=UTC_TIMESTAMP(3)",model);}
    public void failRebuild(UUID id,String error){jdbc.update("update recipe_index_rebuild_job set status='FAILED',last_error=?,completed_at=UTC_TIMESTAMP(3),locked_at=null where id=UUID_TO_BIN(?)",error,id.toString());}
    public String activeCollection(String fallback){String value=jdbc.queryForObject("select active_collection from recipe_search_index_config where singleton_id=1",String.class);return value==null||value.isBlank()?fallback:value;}
    public IndexCounts indexCounts(){Map<String,Long> values=new HashMap<>();jdbc.query("select status,count(*) total from recipe_search_index_state group by status",rs->{values.put(rs.getString("status"),rs.getLong("total"));});return new IndexCounts(values.getOrDefault("READY",0L),values.getOrDefault("MYSQL_ONLY",0L),values.getOrDefault("FAILED",0L));}
    public String activeEmbeddingModel(){return jdbc.queryForObject("select embedding_model_version from recipe_search_index_config where singleton_id=1",String.class);}
    private String toJson(List<String> values){try{return new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(values);}catch(Exception exception){return "[]";}}
    private static String importSelect(){return "select BIN_TO_UUID(id) id,BIN_TO_UUID(source_id) source_id,status,checksum,imported_count,skipped_count,error_count,attempt_count,last_error,created_at,started_at,completed_at from recipe_import_job";}
    private RecipeContracts.ImportJobView importRow(java.sql.ResultSet rs,int n)throws java.sql.SQLException{return new RecipeContracts.ImportJobView(UUID.fromString(rs.getString("id")),UUID.fromString(rs.getString("source_id")),rs.getString("status"),rs.getString("checksum"),rs.getInt("imported_count"),rs.getInt("skipped_count"),rs.getInt("error_count"),rs.getInt("attempt_count"),rs.getString("last_error"),instant(rs.getTimestamp("created_at")),instant(rs.getTimestamp("started_at")),instant(rs.getTimestamp("completed_at")));}
    private static String rebuildSelect(){return "select BIN_TO_UUID(id) id,status,collection_name,embedding_model_version,total_count,processed_count,failure_count,last_error,created_at,started_at,completed_at from recipe_index_rebuild_job";}
    private RecipeContracts.IndexRebuildJobView rebuildRow(java.sql.ResultSet rs,int n)throws java.sql.SQLException{return new RecipeContracts.IndexRebuildJobView(UUID.fromString(rs.getString("id")),rs.getString("status"),rs.getString("collection_name"),rs.getString("embedding_model_version"),rs.getInt("total_count"),rs.getInt("processed_count"),rs.getInt("failure_count"),rs.getString("last_error"),instant(rs.getTimestamp("created_at")),instant(rs.getTimestamp("started_at")),instant(rs.getTimestamp("completed_at")));}
    private PlanRow planRow(java.sql.ResultSet rs,int n)throws java.sql.SQLException{return new PlanRow(UUID.fromString(rs.getString("id")),UUID.fromString(rs.getString("fridge_id")),UUID.fromString(rs.getString("recipe_id")),rs.getBigDecimal("servings"),instant(rs.getTimestamp("created_at")));}
    private Row row(java.sql.ResultSet rs,int n)throws java.sql.SQLException{return new Row(UUID.fromString(rs.getString("id")),rs.getString("title"),rs.getString("summary"),rs.getString("cuisine"),rs.getString("taste"),rs.getString("goal"),rs.getInt("cook_minutes"),rs.getBigDecimal("servings"),rs.getBigDecimal("calories_total"),rs.getBigDecimal("protein_total"),rs.getBigDecimal("fat_total"),rs.getBigDecimal("carbs_total"),rs.getString("nutrition_source"),rs.getString("origin"),rs.getString("source_version"),rs.getString("attribution_text"),rs.getString("image_url"),rs.getString("image_source_url"),rs.getString("image_attribution"));}
    private static Instant instant(Timestamp t){return t==null?null:t.toInstant();}
    public record ImportWork(UUID id,UUID sourceId,String payload,String sourceVersion,String attribution){}
    public record RebuildWork(UUID id,String collectionName,String embeddingModelVersion,int processedCount,int failureCount){}
    public record IndexDocument(UUID id,String title,String content){}
    public record IndexCounts(long ready,long mysqlOnly,long failed){}
    public record PlanRow(UUID id,UUID fridgeId,UUID recipeId,BigDecimal servings,Instant createdAt){}
    public record Row(UUID id,String title,String summary,String cuisine,String taste,String goal,int cookMinutes,BigDecimal servings,BigDecimal calories,BigDecimal protein,BigDecimal fat,BigDecimal carbs,String nutritionSource,String origin,String sourceVersion,String attribution,String imageUrl,String imageSourceUrl,String imageAttribution){}
}
